export default {
    GET_STUDENTS : "GET_STUDENTS",
    ADD_STUDENT : "ADD_STUDENT",
    DELETE_STUDENT : "DELETE_STUDENT",
    GET_ALL_ATTENDANCE: "GET_ALL_ATTENDANCE",
    GET_ATTENDANCE_BY_COURSE: "GET_ATTENDANCE_BY_COURSE",
    GET_ATTENDANCE_BY_DATE_AND_COURSE: "GET_ATTENDANCE_BY_DATE_AND_COURSE",
    SIGNIN: "SIGNIN",
    SIGNUP: "SIGNUP",
    SIGNOUT: "SIGNOUT"
}